In [1]:
import re
import pandas as pd

In [2]:
f=open("WhatsApp Chat with Chivalrous gentlemen.txt",'r',encoding='utf-8')

In [3]:
data=f.read()

In [4]:
print(data)

28/02/2024, 2:12 pm - Messages and calls are end-to-end encrypted. Only people in this chat can read, listen to, or share them. Learn more.
22/12/2023, 7:44 pm - balbasuaar created group "Chivalrous gentlemen"
28/02/2024, 2:12 pm - balbasuaar added you
28/02/2024, 2:13 pm - balbasuaar: Welcome my friend, welcome
28/02/2024, 2:21 pm - Hamza Farhat: "Hello world";
28/02/2024, 2:21 pm - balbasuaar: Hello world ❌ welcome world ✅
28/02/2024, 2:22 pm - Hamza Farhat: Axhaa sirr
28/02/2024, 2:24 pm - Sheemab: 😂😂
28/02/2024, 4:08 pm - balbasuaar: <Media omitted>
28/02/2024, 4:19 pm - Hamza Farhat: Are bhai mubarak ho
28/02/2024, 4:20 pm - Hamza Farhat: Mashallah se
28/02/2024, 4:22 pm - Sheemab: 1present hah
28/02/2024, 4:22 pm - Sheemab: Mashallah
28/02/2024, 4:22 pm - Hamza Farhat: Meri jaan partyyyyy
28/02/2024, 4:22 pm - Sheemab: Allah aurr tarakii de
28/02/2024, 4:22 pm - balbasuaar: <Media omitted>
28/02/2024, 4:22 pm - balbasuaar: <Media omitted>
28/02/2024, 4:24 pm - baby shark: <Media omitted>
28/02/2024, 4:24 pm - balbasuaar: Arey to detain to isme bhi hain 🙂
28/02/2024, 7:13 pm - baby shark: kll aaja rahib khan ek do subject mai detained hone sai bach jawgai
28/02/2024, 7:13 pm - balbasuaar: Dekhta hun yr
28/02/2024, 7:13 pm - baby shark: dekha nhi jaiga baad mai
28/02/2024, 7:41 pm - Sheemab: Aa kr haal dikha ja sir ko apna
28/02/2024, 7:44 pm - baby shark: <Media omitted>
28/02/2024, 7:45 pm - balbasuaar: <Media omitted>
29/02/2024, 2:38 pm - baby shark: <Media omitted>
29/02/2024, 7:10 pm - balbasuaar: Sarey subject me detain hogye kya hum 🙂
29/02/2024, 7:25 pm - Hamza Farhat: Jii
29/02/2024, 7:26 pm - balbasuaar: MAASHALAAAH!
29/02/2024, 7:37 pm - baby shark: Jii
29/02/2024, 7:37 pm - baby shark: Cbnst mainbach gya
29/02/2024, 9:15 pm - Sheemab: 😂😂😂
29/02/2024, 9:53 pm - balbasuaar: <Media omitted>
29/02/2024, 9:53 pm - baby shark: Are Bhai bss
29/02/2024, 9:54 pm - balbasuaar: 😂
29/02/2024, 9:55 pm - baby shark: Bete 100 % bhe aaiga na tuh TB bhe nhi uthe gii ct 1  kai baad
29/02/2024, 9:55 pm - balbasuaar: <Media omitted>
29/02/2024, 9:56 pm - balbasuaar: <Media omitted>
29/02/2024, 9:57 pm - baby shark: Ye to pta chlega
29/02/2024, 9:57 pm - baby shark: 16 mai Sai 1 present
29/02/2024, 9:57 pm - baby shark: Hai abhi tere or mere kitne he cover kr lega
29/02/2024, 9:57 pm - balbasuaar: <Media omitted>
29/02/2024, 10:05 pm - Hamza Farhat: Aslamwalikum
29/02/2024, 10:06 pm - Hamza Farhat: Bhai jaan aap sabko in shaa Allah
29/02/2024, 10:06 pm - Hamza Farhat: Parso raat ko ghar par aana hai dawat h aap sab ki
29/02/2024, 10:06 pm - balbasuaar: Walaikum assalam...habibi
29/02/2024, 10:07 pm - balbasuaar: Arey bhai mashallah mashallah.... Basit khush hogaya
29/02/2024, 10:07 pm - balbasuaar: This message was deleted
29/02/2024, 10:22 pm - balbasuaar: Arey maths to de skta hun me bhi ya nhi
29/02/2024, 10:22 pm - balbasuaar: CT
29/02/2024, 10:26 pm - Sheemab: Walaikum assalam
29/02/2024, 10:26 pm - Hamza Farhat: Tum bss 🍑 ye de sakte ho
29/02/2024, 10:27 pm - Sheemab: Inshallah
29/02/2024, 10:27 pm - balbasuaar: <Media omitted>
29/02/2024, 10:27 pm - Sheemab: 😂😂
29/02/2024, 10:27 pm - Sheemab: Aare hamza yeh bhuri Amma ke chakkar mein phir dewana ho rha hah
29/02/2024, 10:28 pm - Hamza Farhat: Haan yaar aurat
29/02/2024, 10:28 pm - Hamza Farhat: Lagti hai
29/02/2024, 10:37 pm - balbasuaar: <Media omitted>
01/03/2024, 12:29 pm - Sheemab: <Media omitted>
01/03/2024, 3:24 pm - Sheemab: <Media omitted>
01/03/2024, 3:24 pm - baby shark: Bery dangerous
01/03/2024, 6:13 pm - Sheemab: Aare yaar bde karre karre ques hah
01/03/2024, 8:54 pm - Sheemab: <Media omitted>
01/03/2024, 8:54 pm - Sheemab: <Media omitted>
01/03/2024, 9:27 pm - balbasuaar: <Media omitted>
01/03/2024, 9:44 pm - baby shark: <Media omitted>
01/03/2024, 9:44 pm - baby shark: @⁨balbasuaar⁩
01/03/2024, 9:44 pm - balbasuaar: <Media omitted>
01/03/2024, 9:45 pm - baby shark: @⁨Hamza Farhat⁩
@⁨Sheemab⁩ dekh
01/03/2024, 10:03 pm - Sheemab: Jee bdya hai
02/03/2024, 3:14 pm - baby shark: Are Hamza kb ka hai time
02/03/2024, 3:14 pm - Hamza Farhat: Raat ko
02/03/2024, 3:15 pm - baby shark: Thimk
02/03/2024, 4:33 pm - Sheemab: Tym ki hah
02/03/2024, 4:37 pm - Hamza Farhat: 8 vaje tak
02/03/2024, 4:37 pm - Hamza Farhat: Aajaiyee
02/03/2024, 4:55 pm - Sheemab: Thk hah bhai
02/03/2024, 5:40 pm - Hamza Farhat: Aagaye aap rampur
02/03/2024, 6:04 pm - Sheemab: Maghrib ke baad aaunga bhai
02/03/2024, 6:05 pm - baby shark: Aau au
02/03/2024, 6:16 pm - Hamza Farhat: Achaaa
02/03/2024, 6:16 pm - Hamza Farhat: Aaja
02/03/2024, 6:34 pm - baby shark: Mtlb aaram sai aunga
03/03/2024, 9:38 am - Sheemab: Aare 2000 ke notes exchange ho jaenge kya
03/03/2024, 9:38 am - balbasuaar: Na
03/03/2024, 9:38 am - balbasuaar: Jala do ab
03/03/2024, 9:39 am - Sheemab: Chl haathi ke falaan
03/03/2024, 9:39 am - baby shark: Pta nhi yrr
03/03/2024, 9:39 am - balbasuaar: Arey nhi honde kaddu
03/03/2024, 9:39 am - balbasuaar: Gatwe
03/03/2024, 9:39 am - baby shark: Bank mai ho Jain shayad
03/03/2024, 9:39 am - Sheemab: RBI mein honge
03/03/2024, 9:39 am - balbasuaar: Na
03/03/2024, 11:17 am - Hamza Farhat: 🤣
03/03/2024, 11:38 am - Sheemab: NFA
DFS
DFA TO NFA (CONVERSION)
MOORE MACHINE
MEALY MACHINE
CHOMSKY HIERARCHY
03/03/2024, 11:38 am - Sheemab: MEALY TO MOORE
MOORE TO MEALY
CONVERSION
03/03/2024, 11:39 am - Hamza Farhat: <Media omitted>
03/03/2024, 11:39 am - balbasuaar: <Media omitted>
03/03/2024, 11:40 am - Hamza Farhat: Rahib ka bachpan
03/03/2024, 11:40 am - balbasuaar: Wo hi sahi tha yr
03/03/2024, 11:40 am - Sheemab: <Media omitted>
03/03/2024, 11:40 am - balbasuaar: Koi tension nhi
03/03/2024, 11:40 am - Sheemab: <Media omitted>
03/03/2024, 11:40 am - Sheemab: 😂😂
03/03/2024, 11:41 am - baby shark: Are yeh to bca ke hai
03/03/2024, 11:41 am - balbasuaar: Arey neeche dekhle hoosh
03/03/2024, 11:41 am - Hamza Farhat: Koi detain nhi h
03/03/2024, 11:41 am - Hamza Farhat: Seating plan me naam h
03/03/2024, 11:41 am - Hamza Farhat: Paper ke liye
03/03/2024, 11:42 am - Sheemab: Aa jaeyo kya pta Beth he jao
03/03/2024, 11:44 am - baby shark: Yrr kya kro ab. Mai to Bach gya detained sai
03/03/2024, 11:45 am - Sheemab: Kaise pta
03/03/2024, 11:45 am - baby shark: List mai naam hai
03/03/2024, 11:46 am - Sheemab: Hn to thk hah aao jao
03/03/2024, 11:47 am - Sheemab: Jo topic send kiye hah wo kr lo
03/03/2024, 11:47 am - Hamza Farhat: Ye padh lo jo sheemab ne bheja
03/03/2024, 11:47 am - Hamza Farhat: H
03/03/2024, 11:47 am - baby shark: Ek din Mai ho jaonge
03/03/2024, 11:47 am - Hamza Farhat: Haan bhai sab ko ek din me hi karna h
03/03/2024, 11:47 am - Sheemab: Aare kr bhi to
03/03/2024, 11:47 am - baby shark: Chll khane kai baad dekhta hu
03/03/2024, 11:47 am - Sheemab: Abhi betha hu
03/03/2024, 11:47 am - Sheemab: Mein bhi
03/03/2024, 11:48 am - Hamza Farhat: Sheemab ho sake to vedio bhejdio
03/03/2024, 11:48 am - baby shark: @⁨balbasuaar⁩ kha ho
03/03/2024, 11:48 am - balbasuaar: Zameen pr
03/03/2024, 11:50 am - Sheemab: https://youtube.com/playlist?list=PLxCzCOWd7aiFM9Lj5G9G_76adtyb4ef7i
03/03/2024, 11:51 am - Sheemab: Naale prr betha hah
03/03/2024, 11:51 am - balbasuaar: Bete mere sudhar ja
03/03/2024, 11:51 am - balbasuaar: Gatwe
03/03/2024, 12:22 pm - Sheemab: Bhuri kahegi tb he sudhrunga
03/03/2024, 12:38 pm - balbasuaar: Arey chll...
03/03/2024, 4:22 pm - Sheemab: <Media omitted>
03/03/2024, 4:22 pm - Sheemab: <Media omitted>
03/03/2024, 6:36 pm - baby shark: Mai nhi aunga kll
03/03/2024, 6:36 pm - Hamza Farhat: Kyuu
03/03/2024, 6:37 pm - baby shark: Yrr bhai detained hu
03/03/2024, 6:37 pm - Hamza Farhat: Are bhai koi baat nhi
03/03/2024, 6:38 pm - Hamza Farhat: Paper dede
03/03/2024, 6:38 pm - Hamza Farhat: Bss kal
03/03/2024, 6:38 pm - Sheemab: Kon keh rha hah
03/03/2024, 6:38 pm - baby shark: Bhai detained hu
03/03/2024, 6:38 pm - Sheemab: MTT aao bhai jaisi tumhari marzi
03/03/2024, 6:39 pm - baby shark: Omk
03/03/2024, 6:43 pm - Hamza Farhat: Bhai aajao
03/03/2024, 6:43 pm - Hamza Farhat: Koi esi baat nahi h
03/03/2024, 6:43 pm - Hamza Farhat: Agar nahi bethne diya toh ghar chalenge
03/03/2024, 6:44 pm - baby shark: Are bheyye pda nhi hai aakr bhe faida nhi hai
03/03/2024, 6:47 pm - Sheemab: Hn to pdh le
03/03/2024, 6:47 pm - Sheemab: 11:30 se hah
03/03/2024, 6:47 pm - Sheemab: Toc ka
03/03/2024, 6:47 pm - Sheemab: Aurr 2:30 se management ka hah
03/03/2024, 9:46 pm - baby shark: This message was deleted
03/03/2024, 9:50 pm - Sheemab:
03/03/2024, 10:53 pm - baby shark: This message was deleted
04/03/2024, 9:26 am - balbasuaar: Arey paise de diye ? Course ke..
@⁨Hamza Farhat⁩ @⁨baby shark⁩
04/03/2024, 9:57 am - Sheemab: Hnn
04/03/2024, 11:21 am - Hamza Farhat: Haan bhai
04/03/2024, 12:56 pm - Sheemab: Aare last ct waala he paper aa gya
04/03/2024, 12:56 pm - Sheemab: Kaddu short reh gyy
04/03/2024, 12:58 pm - Hamza Farhat: Meri jaan
04/03/2024, 12:58 pm - Hamza Farhat: Maza aagaya
04/03/2024, 12:58 pm - Hamza Farhat: Kisi detain wale bacche ne diya tha kyaa ppr
04/03/2024, 1:00 pm - Sheemab: Naa
04/03/2024, 1:00 pm - Sheemab: Bhai ksi ko nhi deene de rhe hah
04/03/2024, 1:05 pm - Hamza Farhat: <Media omitted>
04/03/2024, 1:09 pm - Sheemab: Bdya meri jaan
04/03/2024, 1:19 pm - baby shark: @⁨Hamza Farhat⁩  gya nhi tu
04/03/2024, 1:29 pm - Hamza Farhat: Nahi yaar
04/03/2024, 1:29 pm - Hamza Farhat: Koi fayda nahi lag raha tha
04/03/2024, 1:34 pm - Sheemab: Bhai nhi deene denge ct
04/03/2024, 1:39 pm - baby shark: Mai to pehle keh rha tha
04/03/2024, 1:39 pm - baby shark: Zaleel kr ke bahar nikala hai mene suna hai
04/03/2024, 1:50 pm - Sheemab: Hnn
05/03/2024, 1:39 pm - Sheemab: Monday se regular aa jaana bhaiyoo. Agrr ct 2 mein detain nhi hoona chahte ho
05/03/2024, 1:45 pm - baby shark: <Media omitted>
05/03/2024, 8:26 pm - Sheemab: <Media omitted>
05/03/2024, 8:26 pm - Sheemab: <Media omitted>
05/03/2024, 8:26 pm - Sheemab: <Media omitted>
05/03/2024, 8:26 pm - Sheemab: <Media omitted>
05/03/2024, 8:26 pm - Sheemab: <Media omitted>
05/03/2024, 8:26 pm - Sheemab: 6ques yeh hah aurr abhi 4 reh gy hah
06/03/2024, 11:40 am - balbasuaar: Yr course Dena ho to deo wrna rehndo ...thik h ..
06/03/2024, 11:41 am - balbasuaar: Salon free ke course ke 500rs leoge mujhse ...
06/03/2024, 11:41 am - balbasuaar: <Media omitted>
06/03/2024, 11:42 am - balbasuaar: Ghaddaron
06/03/2024, 11:53 am - baby shark: Free ka ?
06/03/2024, 11:54 am - baby shark: <Media omitted>
06/03/2024, 11:54 am - balbasuaar: Arey aur kya ...kisi se pta chla mujhe...
06/03/2024, 11:55 am - balbasuaar: Arey yr dono bde harami hain Basit
06/03/2024, 11:55 am - balbasuaar: Mt Dene do yr ... Khud kr lenge
06/03/2024, 11:55 am - baby shark: Kon keh rha hai
06/03/2024, 11:55 am - balbasuaar: Ye jhabra hi keh rha tha kl..
German shepherd
06/03/2024, 11:56 am - balbasuaar: Fir mene ek or se puchha
06/03/2024, 11:57 am - baby shark: Rahib ko Mt Dena guys
06/03/2024, 11:57 am - baby shark: Kn ?
06/03/2024, 12:16 pm - balbasuaar: Hamza
06/03/2024, 12:16 pm - baby shark: Tune kisse pucha
06/03/2024, 12:16 pm - balbasuaar: Arey mt deo yr ......
06/03/2024, 12:17 pm - balbasuaar: Section c ka ek ladka h
06/03/2024, 12:17 pm - baby shark: Done
06/03/2024, 12:17 pm - balbasuaar: Naam nhi btaunga
06/03/2024, 12:29 pm - Hamza Farhat: Basit tujhe mil jayega aaj
06/03/2024, 12:29 pm - Hamza Farhat: Theek h
06/03/2024, 12:47 pm - Sheemab: Leo beete hamza ne to de diya ct
06/03/2024, 12:47 pm - baby shark: Done
06/03/2024, 12:48 pm - baby shark: Next time Bombay centralisty is the next time
06/03/2024, 12:49 pm - baby shark: @⁨Sheemab⁩  rahib kya keh rha hai
06/03/2024, 12:49 pm - Sheemab: Falaan free ke
06/03/2024, 12:50 pm - Sheemab: Kya keh rha hah
06/03/2024, 12:57 pm - Hamza Farhat: Keh raha h
06/03/2024, 12:57 pm - Hamza Farhat: Gaddaro
06/03/2024, 12:57 pm - Hamza Farhat: Sheemab gaddar keh raha h
06/03/2024, 12:57 pm - Hamza Farhat: Iske paas aa na jaaye
06/03/2024, 12:57 pm - Hamza Farhat: Course
06/03/2024, 1:14 pm - Sheemab: Jb tk 500 nhi deega
06/03/2024, 1:15 pm - Sheemab: Tb nhi jaana chahiye iske pass
06/03/2024, 1:18 pm - balbasuaar: Arey chl mt Dey.....
1 rs bhi nhi dunga ...
06/03/2024, 1:29 pm - Sheemab: Thk hah
06/03/2024, 1:29 pm - Sheemab: Maang MTT liye ab bta rha hu
06/03/2024, 1:29 pm - baby shark: Ab kis ka paper haib
06/03/2024, 1:29 pm - Hamza Farhat: O s
Cbnst
06/03/2024, 1:30 pm - Sheemab: Saturday ko hah
06/03/2024, 1:30 pm - baby shark: Dedu kya kru
06/03/2024, 1:30 pm - Sheemab: Hn aur kya
06/03/2024, 1:30 pm - Sheemab: Saare ct deo ab
06/03/2024, 1:30 pm - Sheemab: Jo bhi reh gy hah
06/03/2024, 1:31 pm - baby shark: Send kr diu padne ka
06/03/2024, 1:43 pm - Sheemab: Tomorrow
06/03/2024, 1:44 pm - Sheemab: Personaly kr dunga tujhe aur hamza ko
06/03/2024, 1:44 pm - Sheemab: Rahib ko send MTT krna
06/03/2024, 2:01 pm - baby shark: <Media omitted>
06/03/2024, 2:01 pm - baby shark: This message was deleted
07/03/2024, 10:44 am - Sheemab: <Media omitted>
07/03/2024, 4:03 pm - Sheemab: <Media omitted>
07/03/2024, 4:03 pm - Sheemab: 2method hah yeh 2aurr reh gy hah 1unit se
07/03/2024, 4:04 pm - balbasuaar: Kitne unit aa rhe h
07/03/2024, 4:04 pm - Sheemab: 2
07/03/2024, 4:04 pm - balbasuaar: Easy konsa h
07/03/2024, 4:05 pm - Sheemab: First waala bht easy hah
07/03/2024, 4:05 pm - Sheemab: Aur last year ke ct paper ke short answer kr Leena
07/03/2024, 4:05 pm - Sheemab: 20tkk aa jenge inshallah
07/03/2024, 4:05 pm - balbasuaar: Ok
07/03/2024, 4:06 pm - Sheemab: Gende ke falaan ke 500 rupee Dede agr course Leena ho tb
07/03/2024, 4:06 pm - Hamza Farhat: 🤣
07/03/2024, 4:06 pm - balbasuaar: Bhk
07/03/2024, 4:06 pm - balbasuaar: Mt de
07/03/2024, 4:06 pm - balbasuaar: Aesi dena h to h
07/03/2024, 4:06 pm - balbasuaar: Gtwe
07/03/2024, 4:06 pm - Hamza Farhat: Sheemab aa nahi jaye iske paas
07/03/2024, 4:06 pm - Hamza Farhat: Course kahi s bhi
07/03/2024, 4:07 pm - balbasuaar: Itni tension Mt le. Nhi ayega
07/03/2024, 4:07 pm - Sheemab: Katai nhi bhai
07/03/2024, 4:07 pm - Hamza Farhat: Dekh le ise
07/03/2024, 4:07 pm - Hamza Farhat: 🤣
07/03/2024, 4:07 pm - Sheemab: 😂😂😂
07/03/2024, 4:08 pm - balbasuaar: 😁
07/03/2024, 4:08 pm - Hamza Farhat: Gende ka fallaan
07/03/2024, 4:08 pm - Hamza Farhat: 🤣🤣
07/03/2024, 4:08 pm - balbasuaar: German shepherd
07/03/2024, 4:08 pm - Sheemab: 😂😂
07/03/2024, 4:08 pm - balbasuaar: Gtwa hasa
07/03/2024, 4:08 pm - balbasuaar: 😂
07/03/2024, 4:09 pm - Sheemab: Iska alag meaning hah
07/03/2024, 4:09 pm - Hamza Farhat: Chutar ki booti me kaatunga kisi din tere
07/03/2024, 4:09 pm - Sheemab: Aurr iska alag hai
07/03/2024, 4:09 pm - Sheemab: 😂😂😂
07/03/2024, 4:09 pm - Hamza Farhat: 14 injection 💉 pakke hein
07/03/2024, 4:09 pm - Hamza Farhat: Saale galti se mistake
07/03/2024, 4:09 pm - balbasuaar: Maan Kiya janwar ho 🙂
07/03/2024, 4:09 pm - Hamza Farhat: Kiya nahi liyaa
07/03/2024, 4:10 pm - balbasuaar: Man liya
07/03/2024, 4:10 pm - Hamza Farhat: Tu Haadse me ho gaya tha
07/03/2024, 4:10 pm - Sheemab: 😂😂
07/03/2024, 4:10 pm - balbasuaar: Or tuuu
07/03/2024, 4:10 pm - Hamza Farhat: Tere papa oops karte reh gaye
07/03/2024, 4:10 pm - Hamza Farhat: Sunnat se
07/03/2024, 4:10 pm - Sheemab: Pachta rhe hah beechare kr ke ise
07/03/2024, 4:10 pm - Sheemab: 😂😂
07/03/2024, 4:11 pm - Hamza Farhat: Ab to haste rehte hein
07/03/2024, 4:11 pm - balbasuaar: Dekha tha usdin ...
07/03/2024, 4:11 pm - Hamza Farhat: Rahib aaraam se typing kar kahi kandha utar jaye
07/03/2024, 4:12 pm - Sheemab: 😂😂
07/03/2024, 4:12 pm - Hamza Farhat: Unhone bhi dekha tha unki pant pehna hua tha
07/03/2024, 4:13 pm - balbasuaar: <Media omitted>
07/03/2024, 4:13 pm - Hamza Farhat: Tera intezaar kar raha hun
07/03/2024, 4:13 pm - Hamza Farhat: Doggy banakr lunga teri
07/03/2024, 4:14 pm - balbasuaar: Arey tujhe to Teri biwi na de
07/03/2024, 4:15 pm - Hamza Farhat: Teri to dedegi
07/03/2024, 4:15 pm - Hamza Farhat: Koi pareshaani thodi h
07/03/2024, 4:15 pm - Hamza Farhat: Rahib 10th class ki tution padha lega
07/03/2024, 4:16 pm - balbasuaar: <Media omitted>
07/03/2024, 4:16 pm - Hamza Farhat: <Media omitted>
07/03/2024, 4:16 pm - Hamza Farhat: Bete baal to hein
07/03/2024, 4:17 pm - balbasuaar: Bina balon ka insan achcha...
07/03/2024, 4:17 pm - Hamza Farhat: Apna introduction dediya
07/03/2024, 4:17 pm - Hamza Farhat: Tune
07/03/2024, 4:18 pm - balbasuaar: Hn bhyye janwar to nhi hun
07/03/2024, 4:18 pm - Hamza Farhat: Kon tu
09/03/2024, 10:20 am - Sheemab: Bsdk ke rahib dekh le bht kehta hah aacha gya
09/03/2024, 10:20 am - Sheemab: Bht he bekaar vaheyaat ct gya aaj ja
09/03/2024, 10:20 am - Sheemab: Ka
09/03/2024, 10:20 am - baby shark: Ku
09/03/2024, 10:20 am - Sheemab: 5 aa Jay to bht hah
09/03/2024, 10:21 am - Sheemab: Aare aata he kb tha
09/03/2024, 10:21 am - Sheemab: Kaddu
09/03/2024, 10:21 am - baby shark: Cbnst kantha na
09/03/2024, 10:21 am - Sheemab: Hnn
09/03/2024, 10:21 am - Hamza Farhat: Achaa hua nahi aaya
09/03/2024, 10:21 am - Hamza Farhat: 1 marks ka nahi aata tha
09/03/2024, 10:21 am - baby shark: 👍😉
09/03/2024, 10:29 am - balbasuaar: Paper bhejio
09/03/2024, 10:31 am - Sheemab: 500 de
09/03/2024, 10:32 am - Sheemab: Falaan ka photo send kr du
09/03/2024, 10:32 am - Sheemab: Jitna khatarnak paper hah itna he falaan hah
09/03/2024, 10:32 am - balbasuaar: Arey ye bheek mangney ki adat kb ko jayegi Teri gtwe
09/03/2024, 10:33 am - Sheemab: Teri gaand thodi maang rha hu bheek mein
09/03/2024, 12:01 pm - Sheemab: Operating system ka pdh lo firando
09/03/2024, 12:01 pm - Sheemab: <Media omitted>
10/03/2024, 9:25 pm - baby shark: Are kll ana hai ya kll kai baad ana hai
10/03/2024, 9:26 pm - Hamza Farhat: Kl se
10/03/2024, 9:26 pm - balbasuaar: Arey kl ana h yr
10/03/2024, 9:31 pm - baby shark: Chlo thik hai INSHALLAH
11/03/2024, 6:52 am - Sheemab: Aasalamualaikum
11/03/2024, 6:52 am - Sheemab: Aa rhe ho kya
11/03/2024, 6:52 am - baby shark: WALEKUM ASSALAM
11/03/2024, 6:52 am - baby shark: H
11/03/2024, 6:52 am - baby shark: Tu
11/03/2024, 6:52 am - Sheemab: Hn
11/03/2024, 6:52 am - baby shark: Very good
11/03/2024, 6:53 am - Sheemab: Very dangerous
11/03/2024, 7:09 am - balbasuaar: Gud hain
11/03/2024, 6:52 pm - baby shark: <Media omitted>
11/03/2024, 7:54 pm - balbasuaar: <Media omitted>
11/03/2024, 9:53 pm - balbasuaar: Kya krna h kl ka 🙃 <This message was edited>
11/03/2024, 10:22 pm - balbasuaar: <Media omitted>
12/03/2024, 4:44 am - Sheemab: Aj ka mushkil hah
12/03/2024, 4:44 am - Hamza Farhat: Abe aajaiyo
12/03/2024, 4:45 am - Hamza Farhat: Kya karenge ghar pr bhi
12/03/2024, 4:50 am - balbasuaar: Kiiiiiuuuunnn
12/03/2024, 5:13 am - Sheemab: Yaar neeind nhi hui hah
12/03/2024, 5:13 am - Sheemab: Bhai mere
12/03/2024, 5:15 am - Hamza Farhat: Are aajauiyo
12/03/2024, 1:35 pm - baby shark: @⁨Hamza Farhat⁩  kha hai
12/03/2024, 7:46 pm - balbasuaar: Bs 29 roze reh gye .. pta hi nhi chla 🙃
12/03/2024, 8:00 pm - Hamza Farhat: Toh rakhlo
12/03/2024, 8:00 pm - Hamza Farhat: Tabhi toh pata chalenge
12/03/2024, 9:28 pm - Sheemab: 😁😁😁
12/03/2024, 9:28 pm - Sheemab: Bhaag bhaag ke aa rhe ho clg se pta kya chlega
12/03/2024, 9:34 pm - balbasuaar: <Media omitted>
12/03/2024, 9:56 pm - Hamza Farhat: Bhai abhi 12 tarabeh hui hein
12/03/2024, 9:56 pm - Hamza Farhat: Or turion bhi h iske baad
12/03/2024, 9:56 pm - Hamza Farhat: Mai kl se takiya launga
12/03/2024, 9:56 pm - Hamza Farhat: Bag me
12/03/2024, 9:56 pm - Hamza Farhat: Soounga
12/03/2024, 9:59 pm - Sheemab: 😁😁😁
12/03/2024, 9:59 pm - Sheemab: Yha to bht tym ki hoo gyy
12/03/2024, 9:59 pm - Sheemab: Ooo bhaii
12/03/2024, 10:16 pm - baby shark: Kll nhi aunga
12/03/2024, 10:16 pm - baby shark: 1 lab hai 1 sih hai Java vale sai baat hogue hai cbnst mai thik thak hai
12/03/2024, 10:16 pm - baby shark: <Media omitted>
13/03/2024, 5:20 am - balbasuaar: @⁨baby shark⁩ ayega
13/03/2024, 5:21 am - Hamza Farhat: Tu jayega
13/03/2024, 5:21 am - balbasuaar: Hmm
13/03/2024, 5:22 am - balbasuaar: Shyd 😁
13/03/2024, 5:22 am - Hamza Farhat: Achaa
13/03/2024, 5:22 am - Sheemab: Mein bhi aaunga inshallah
13/03/2024, 5:22 am - Hamza Farhat: In shaa Allah

In [5]:
# pattern = r"\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s?(?:am|pm)?\s-\s"
pattern = r"\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}\s*(?:am|pm)\s-\s"

In [6]:
messages=re.split(pattern, data)
len(messages)

4011

In [7]:
dates=re.findall(pattern,data)
dates

['28/02/2024, 2:12\u202fpm - ',
 '22/12/2023, 7:44\u202fpm - ',
 '28/02/2024, 2:12\u202fpm - ',
 '28/02/2024, 2:13\u202fpm - ',
 '28/02/2024, 2:21\u202fpm - ',
 '28/02/2024, 2:21\u202fpm - ',
 '28/02/2024, 2:22\u202fpm - ',
 '28/02/2024, 2:24\u202fpm - ',
 '28/02/2024, 4:08\u202fpm - ',
 '28/02/2024, 4:19\u202fpm - ',
 '28/02/2024, 4:20\u202fpm - ',
 '28/02/2024, 4:22\u202fpm - ',
 '28/02/2024, 4:22\u202fpm - ',
 '28/02/2024, 4:22\u202fpm - ',
 '28/02/2024, 4:22\u202fpm - ',
 '28/02/2024, 4:22\u202fpm - ',
 '28/02/2024, 4:22\u202fpm - ',
 '28/02/2024, 4:24\u202fpm - ',
 '28/02/2024, 4:24\u202fpm - ',
 '28/02/2024, 7:13\u202fpm - ',
 '28/02/2024, 7:13\u202fpm - ',
 '28/02/2024, 7:13\u202fpm - ',
 '28/02/2024, 7:41\u202fpm - ',
 '28/02/2024, 7:44\u202fpm - ',
 '28/02/2024, 7:45\u202fpm - ',
 '29/02/2024, 2:38\u202fpm - ',
 '29/02/2024, 7:10\u202fpm - ',
 '29/02/2024, 7:25\u202fpm - ',
 '29/02/2024, 7:26\u202fpm - ',
 '29/02/2024, 7:37\u202fpm - ',
 '29/02/2024, 7:37\u202fpm - ',
 '29/02/2024, 9:15\u202fpm - ',
 '29/02/2024, 9:53\u202fpm - ',
 '29/02/2024, 9:53\u202fpm - ',
 '29/02/2024, 9:54\u202fpm - ',
 '29/02/2024, 9:55\u202fpm - ',
 '29/02/2024, 9:55\u202fpm - ',
 '29/02/2024, 9:56\u202fpm - ',
 '29/02/2024, 9:57\u202fpm - ',
 '29/02/2024, 9:57\u202fpm - ',
 '29/02/2024, 9:57\u202fpm - ',
 '29/02/2024, 9:57\u202fpm - ',
 '29/02/2024, 10:05\u202fpm - ',
 '29/02/2024, 10:06\u202fpm - ',
 '29/02/2024, 10:06\u202fpm - ',
 '29/02/2024, 10:06\u202fpm - ',
 '29/02/2024, 10:07\u202fpm - ',
 '29/02/2024, 10:07\u202fpm - ',
 '29/02/2024, 10:22\u202fpm - ',
 '29/02/2024, 10:22\u202fpm - ',
 '29/02/2024, 10:26\u202fpm - ',
 '29/02/2024, 10:26\u202fpm - ',
 '29/02/2024, 10:27\u202fpm - ',
 '29/02/2024, 10:27\u202fpm - ',
 '29/02/2024, 10:27\u202fpm - ',
 '29/02/2024, 10:27\u202fpm - ',
 '29/02/2024, 10:28\u202fpm - ',
 '29/02/2024, 10:28\u202fpm - ',
 '29/02/2024, 10:37\u202fpm - ',
 '01/03/2024, 12:29\u202fpm - ',
 '01/03/2024, 3:24\u202fpm - ',
 '01/03/2024, 3:24\u202fpm - ',
 '01/03/2024, 6:13\u202fpm - ',
 '01/03/2024, 8:54\u202fpm - ',
 '01/03/2024, 8:54\u202fpm - ',
 '01/03/2024, 9:27\u202fpm - ',
 '01/03/2024, 9:44\u202fpm - ',
 '01/03/2024, 9:44\u202fpm - ',
 '01/03/2024, 9:44\u202fpm - ',
 '01/03/2024, 9:45\u202fpm - ',
 '01/03/2024, 10:03\u202fpm - ',
 '02/03/2024, 3:14\u202fpm - ',
 '02/03/2024, 3:14\u202fpm - ',
 '02/03/2024, 3:15\u202fpm - ',
 '02/03/2024, 4:33\u202fpm - ',
 '02/03/2024, 4:37\u202fpm - ',
 '02/03/2024, 4:37\u202fpm - ',
 '02/03/2024, 4:55\u202fpm - ',
 '02/03/2024, 5:40\u202fpm - ',
 '02/03/2024, 6:04\u202fpm - ',
 '02/03/2024, 6:05\u202fpm - ',
 '02/03/2024, 6:16\u202fpm - ',
 '02/03/2024, 6:16\u202fpm - ',
 '02/03/2024, 6:34\u202fpm - ',
 '03/03/2024, 9:38\u202fam - ',
 '03/03/2024, 9:38\u202fam - ',
 '03/03/2024, 9:38\u202fam - ',
 '03/03/2024, 9:39\u202fam - ',
 '03/03/2024, 9:39\u202fam - ',
 '03/03/2024, 9:39\u202fam - ',
 '03/03/2024, 9:39\u202fam - ',
 '03/03/2024, 9:39\u202fam - ',
 '03/03/2024, 9:39\u202fam - ',
 '03/03/2024, 9:39\u202fam - ',
 '03/03/2024, 11:17\u202fam - ',
 '03/03/2024, 11:38\u202fam - ',
 '03/03/2024, 11:38\u202fam - ',
 '03/03/2024, 11:39\u202fam - ',
 '03/03/2024, 11:39\u202fam - ',
 '03/03/2024, 11:40\u202fam - ',
 '03/03/2024, 11:40\u202fam - ',
 '03/03/2024, 11:40\u202fam - ',
 '03/03/2024, 11:40\u202fam - ',
 '03/03/2024, 11:40\u202fam - ',
 '03/03/2024, 11:40\u202fam - ',
 '03/03/2024, 11:41\u202fam - ',
 '03/03/2024, 11:41\u202fam - ',
 '03/03/2024, 11:41\u202fam - ',
 '03/03/2024, 11:41\u202fam - ',
 '03/03/2024, 11:41\u202fam - ',
 '03/03/2024, 11:42\u202fam - ',
 '03/03/2024, 11:44\u202fam - ',
 '03/03/2024, 11:45\u202fam - ',
 '03/03/2024, 11:45\u202fam - ',
 '03/03/2024, 11:46\u202fam - ',
 '03/03/2024, 11:47\u202fam - ',
 '03/03/2024, 11:47\u202fam - ',
 '03/03/2024, 11:47\u202fam - ',
 '03/03/2024, 11:47\u202fam - ',
 '03/03/2024, 11:47\u202fam - ',
 '03/03/2024, 11:47\u202fam - ',
 '03/03/2024, 11:47\u202fam - ',
 '03/03/2024, 11:47\u202fam - ',
 '03/03/2024, 11:47\u202fam - ',
 '03/03/2024, 11:48\u202fam - ',
 '03/03/2024, 11:48\u202fam - ',
 '03/03/2024, 11:48\u202fam - ',
 '03/03/2024, 11:50\u202fam - ',
 '03/03/2024, 11:51\u202fam - ',
 '03/03/2024, 11:51\u202fam - ',
 '03/03/2024, 11:51\u202fam - ',
 '03/03/2024, 12:22\u202fpm - ',
 '03/03/2024, 12:38\u202fpm - ',
 '03/03/2024, 4:22\u202fpm - ',
 '03/03/2024, 4:22\u202fpm - ',
 '03/03/2024, 6:36\u202fpm - ',
 '03/03/2024, 6:36\u202fpm - ',
 '03/03/2024, 6:37\u202fpm - ',
 '03/03/2024, 6:37\u202fpm - ',
 '03/03/2024, 6:38\u202fpm - ',
 '03/03/2024, 6:38\u202fpm - ',
 '03/03/2024, 6:38\u202fpm - ',
 '03/03/2024, 6:38\u202fpm - ',
 '03/03/2024, 6:38\u202fpm - ',
 '03/03/2024, 6:39\u202fpm - ',
 '03/03/2024, 6:43\u202fpm - ',
 '03/03/2024, 6:43\u202fpm - ',
 '03/03/2024, 6:43\u202fpm - ',
 '03/03/2024, 6:44\u202fpm - ',
 '03/03/2024, 6:47\u202fpm - ',
 '03/03/2024, 6:47\u202fpm - ',
 '03/03/2024, 6:47\u202fpm - ',
 '03/03/2024, 6:47\u202fpm - ',
 '03/03/2024, 9:46\u202fpm - ',
 '03/03/2024, 9:50\u202fpm - ',
 '03/03/2024, 10:53\u202fpm - ',
 '04/03/2024, 9:26\u202fam - ',
 '04/03/2024, 9:57\u202fam - ',
 '04/03/2024, 11:21\u202fam - ',
 '04/03/2024, 12:56\u202fpm - ',
 '04/03/2024, 12:56\u202fpm - ',
 '04/03/2024, 12:58\u202fpm - ',
 '04/03/2024, 12:58\u202fpm - ',
 '04/03/2024, 12:58\u202fpm - ',
 '04/03/2024, 1:00\u202fpm - ',
 '04/03/2024, 1:00\u202fpm - ',
 '04/03/2024, 1:05\u202fpm - ',
 '04/03/2024, 1:09\u202fpm - ',
 '04/03/2024, 1:19\u202fpm - ',
 '04/03/2024, 1:29\u202fpm - ',
 '04/03/2024, 1:29\u202fpm - ',
 '04/03/2024, 1:34\u202fpm - ',
 '04/03/2024, 1:39\u202fpm - ',
 '04/03/2024, 1:39\u202fpm - ',
 '04/03/2024, 1:50\u202fpm - ',
 '05/03/2024, 1:39\u202fpm - ',
 '05/03/2024, 1:45\u202fpm - ',
 '05/03/2024, 8:26\u202fpm - ',
 '05/03/2024, 8:26\u202fpm - ',
 '05/03/2024, 8:26\u202fpm - ',
 '05/03/2024, 8:26\u202fpm - ',
 '05/03/2024, 8:26\u202fpm - ',
 '05/03/2024, 8:26\u202fpm - ',
 '06/03/2024, 11:40\u202fam - ',
 '06/03/2024, 11:41\u202fam - ',
 '06/03/2024, 11:41\u202fam - ',
 '06/03/2024, 11:42\u202fam - ',
 '06/03/2024, 11:53\u202fam - ',
 '06/03/2024, 11:54\u202fam - ',
 '06/03/2024, 11:54\u202fam - ',
 '06/03/2024, 11:55\u202fam - ',
 '06/03/2024, 11:55\u202fam - ',
 '06/03/2024, 11:55\u202fam - ',
 '06/03/2024, 11:55\u202fam - ',
 '06/03/2024, 11:56\u202fam - ',
 '06/03/2024, 11:57\u202fam - ',
 '06/03/2024, 11:57\u202fam - ',
 '06/03/2024, 12:16\u202fpm - ',
 '06/03/2024, 12:16\u202fpm - ',
 '06/03/2024, 12:16\u202fpm - ',
 '06/03/2024, 12:17\u202fpm - ',
 '06/03/2024, 12:17\u202fpm - ',
 '06/03/2024, 12:17\u202fpm - ',
 '06/03/2024, 12:29\u202fpm - ',
 '06/03/2024, 12:29\u202fpm - ',
 '06/03/2024, 12:47\u202fpm - ',
 '06/03/2024, 12:47\u202fpm - ',
 '06/03/2024, 12:48\u202fpm - ',
 '06/03/2024, 12:49\u202fpm - ',
 '06/03/2024, 12:49\u202fpm - ',
 '06/03/2024, 12:50\u202fpm - ',
 '06/03/2024, 12:57\u202fpm - ',
 '06/03/2024, 12:57\u202fpm - ',
 '06/03/2024, 12:57\u202fpm - ',
 '06/03/2024, 12:57\u202fpm - ',
 '06/03/2024, 12:57\u202fpm - ',
 '06/03/2024, 1:14\u202fpm - ',
 '06/03/2024, 1:15\u202fpm - ',
 '06/03/2024, 1:18\u202fpm - ',
 '06/03/2024, 1:29\u202fpm - ',
 '06/03/2024, 1:29\u202fpm - ',
 '06/03/2024, 1:29\u202fpm - ',
 '06/03/2024, 1:29\u202fpm - ',
 '06/03/2024, 1:30\u202fpm - ',
 '06/03/2024, 1:30\u202fpm - ',
 '06/03/2024, 1:30\u202fpm - ',
 '06/03/2024, 1:30\u202fpm - ',
 '06/03/2024, 1:30\u202fpm - ',
 '06/03/2024, 1:31\u202fpm - ',
 '06/03/2024, 1:43\u202fpm - ',
 '06/03/2024, 1:44\u202fpm - ',
 '06/03/2024, 1:44\u202fpm - ',
 '06/03/2024, 2:01\u202fpm - ',
 '06/03/2024, 2:01\u202fpm - ',
 '07/03/2024, 10:44\u202fam - ',
 '07/03/2024, 4:03\u202fpm - ',
 '07/03/2024, 4:03\u202fpm - ',
 '07/03/2024, 4:04\u202fpm - ',
 '07/03/2024, 4:04\u202fpm - ',
 '07/03/2024, 4:04\u202fpm - ',
 '07/03/2024, 4:05\u202fpm - ',
 '07/03/2024, 4:05\u202fpm - ',
 '07/03/2024, 4:05\u202fpm - ',
 '07/03/2024, 4:05\u202fpm - ',
 '07/03/2024, 4:06\u202fpm - ',
 '07/03/2024, 4:06\u202fpm - ',
 '07/03/2024, 4:06\u202fpm - ',
 '07/03/2024, 4:06\u202fpm - ',
 '07/03/2024, 4:06\u202fpm - ',
 '07/03/2024, 4:06\u202fpm - ',
 '07/03/2024, 4:06\u202fpm - ',
 '07/03/2024, 4:06\u202fpm - ',
 '07/03/2024, 4:07\u202fpm - ',
 '07/03/2024, 4:07\u202fpm - ',
 '07/03/2024, 4:07\u202fpm - ',
 '07/03/2024, 4:07\u202fpm - ',
 '07/03/2024, 4:07\u202fpm - ',
 '07/03/2024, 4:08\u202fpm - ',
 '07/03/2024, 4:08\u202fpm - ',
 '07/03/2024, 4:08\u202fpm - ',
 '07/03/2024, 4:08\u202fpm - ',
 '07/03/2024, 4:08\u202fpm - ',
 '07/03/2024, 4:08\u202fpm - ',
 '07/03/2024, 4:08\u202fpm - ',
 '07/03/2024, 4:09\u202fpm - ',
 '07/03/2024, 4:09\u202fpm - ',
 '07/03/2024, 4:09\u202fpm - ',
 '07/03/2024, 4:09\u202fpm - ',
 '07/03/2024, 4:09\u202fpm - ',
 '07/03/2024, 4:09\u202fpm - ',
 '07/03/2024, 4:09\u202fpm - ',
 '07/03/2024, 4:09\u202fpm - ',
 '07/03/2024, 4:10\u202fpm - ',
 '07/03/2024, 4:10\u202fpm - ',
 '07/03/2024, 4:10\u202fpm - ',
 '07/03/2024, 4:10\u202fpm - ',
 '07/03/2024, 4:10\u202fpm - ',
 '07/03/2024, 4:10\u202fpm - ',
 '07/03/2024, 4:10\u202fpm - ',
 '07/03/2024, 4:10\u202fpm - ',
 '07/03/2024, 4:11\u202fpm - ',
 '07/03/2024, 4:11\u202fpm - ',
 '07/03/2024, 4:11\u202fpm - ',
 '07/03/2024, 4:12\u202fpm - ',
 '07/03/2024, 4:12\u202fpm - ',
 '07/03/2024, 4:13\u202fpm - ',
 '07/03/2024, 4:13\u202fpm - ',
 '07/03/2024, 4:13\u202fpm - ',
 '07/03/2024, 4:14\u202fpm - ',
 '07/03/2024, 4:15\u202fpm - ',
 '07/03/2024, 4:15\u202fpm - ',
 '07/03/2024, 4:15\u202fpm - ',
 '07/03/2024, 4:16\u202fpm - ',
 '07/03/2024, 4:16\u202fpm - ',
 '07/03/2024, 4:16\u202fpm - ',
 '07/03/2024, 4:17\u202fpm - ',
 '07/03/2024, 4:17\u202fpm - ',
 '07/03/2024, 4:17\u202fpm - ',
 '07/03/2024, 4:18\u202fpm - ',
 '07/03/2024, 4:18\u202fpm - ',
 '09/03/2024, 10:20\u202fam - ',
 '09/03/2024, 10:20\u202fam - ',
 '09/03/2024, 10:20\u202fam - ',
 '09/03/2024, 10:20\u202fam - ',
 '09/03/2024, 10:20\u202fam - ',
 '09/03/2024, 10:21\u202fam - ',
 '09/03/2024, 10:21\u202fam - ',
 '09/03/2024, 10:21\u202fam - ',
 '09/03/2024, 10:21\u202fam - ',
 '09/03/2024, 10:21\u202fam - ',
 '09/03/2024, 10:21\u202fam - ',
 '09/03/2024, 10:21\u202fam - ',
 '09/03/2024, 10:29\u202fam - ',
 '09/03/2024, 10:31\u202fam - ',
 '09/03/2024, 10:32\u202fam - ',
 '09/03/2024, 10:32\u202fam - ',
 '09/03/2024, 10:32\u202fam - ',
 '09/03/2024, 10:33\u202fam - ',
 '09/03/2024, 12:01\u202fpm - ',
 '09/03/2024, 12:01\u202fpm - ',
 '10/03/2024, 9:25\u202fpm - ',
 '10/03/2024, 9:26\u202fpm - ',
 '10/03/2024, 9:26\u202fpm - ',
 '10/03/2024, 9:31\u202fpm - ',
 '11/03/2024, 6:52\u202fam - ',
 '11/03/2024, 6:52\u202fam - ',
 '11/03/2024, 6:52\u202fam - ',
 '11/03/2024, 6:52\u202fam - ',
 '11/03/2024, 6:52\u202fam - ',
 '11/03/2024, 6:52\u202fam - ',
 '11/03/2024, 6:52\u202fam - ',
 '11/03/2024, 6:53\u202fam - ',
 '11/03/2024, 7:09\u202fam - ',
 '11/03/2024, 6:52\u202fpm - ',
 '11/03/2024, 7:54\u202fpm - ',
 '11/03/2024, 9:53\u202fpm - ',
 '11/03/2024, 10:22\u202fpm - ',
 '12/03/2024, 4:44\u202fam - ',
 '12/03/2024, 4:44\u202fam - ',
 '12/03/2024, 4:45\u202fam - ',
 '12/03/2024, 4:50\u202fam - ',
 '12/03/2024, 5:13\u202fam - ',
 '12/03/2024, 5:13\u202fam - ',
 '12/03/2024, 5:15\u202fam - ',
 '12/03/2024, 1:35\u202fpm - ',
 '12/03/2024, 7:46\u202fpm - ',
 '12/03/2024, 8:00\u202fpm - ',
 '12/03/2024, 8:00\u202fpm - ',
 '12/03/2024, 9:28\u202fpm - ',
 '12/03/2024, 9:28\u202fpm - ',
 '12/03/2024, 9:34\u202fpm - ',
 '12/03/2024, 9:56\u202fpm - ',
 '12/03/2024, 9:56\u202fpm - ',
 '12/03/2024, 9:56\u202fpm - ',
 '12/03/2024, 9:56\u202fpm - ',
 '12/03/2024, 9:56\u202fpm - ',
 '12/03/2024, 9:59\u202fpm - ',
 '12/03/2024, 9:59\u202fpm - ',
 '12/03/2024, 9:59\u202fpm - ',
 '12/03/2024, 10:16\u202fpm - ',
 '12/03/2024, 10:16\u202fpm - ',
 '12/03/2024, 10:16\u202fpm - ',
 '13/03/2024, 5:20\u202fam - ',
 '13/03/2024, 5:21\u202fam - ',
 '13/03/2024, 5:21\u202fam - ',
 '13/03/2024, 5:22\u202fam - ',
 '13/03/2024, 5:22\u202fam - ',
 '13/03/2024, 5:22\u202fam - ',
 '13/03/2024, 5:22\u202fam - ',
 '13/03/2024, 5:22\u202fam - ',
 '13/03/2024, 5:22\u202fam - ',
 '13/03/2024, 5:22\u202fam - ',
 '13/03/2024, 5:23\u202fam - ',
 '13/03/2024, 5:23\u202fam - ',
 '13/03/2024, 5:23\u202fam - ',
 '13/03/2024, 5:23\u202fam - ',
 '13/03/2024, 5:44\u202fam - ',
 '13/03/2024, 5:49\u202fam - ',
 '14/03/2024, 4:46\u202fam - ',
 '14/03/2024, 4:47\u202fam - ',
 '14/03/2024, 4:47\u202fam - ',
 '14/03/2024, 4:47\u202fam - ',
 '14/03/2024, 4:48\u202fam - ',
 '14/03/2024, 4:48\u202fam - ',
 '14/03/2024, 4:48\u202fam - ',
 '14/03/2024, 4:48\u202fam - ',
 '14/03/2024, 4:49\u202fam - ',
 '14/03/2024, 4:50\u202fam - ',
 '14/03/2024, 4:50\u202fam - ',
 '14/03/2024, 4:54\u202fam - ',
 '14/03/2024, 5:00\u202fam - ',
 '14/03/2024, 5:00\u202fam - ',
 '14/03/2024, 6:59\u202fam - ',
 '14/03/2024, 9:58\u202fam - ',
 '15/03/2024, 12:17\u202fam - ',
 '15/03/2024, 12:17\u202fam - ',
 '15/03/2024, 5:13\u202fam - ',
 '15/03/2024, 11:04\u202fam - ',
 '15/03/2024, 6:48\u202fpm - ',
 '15/03/2024, 6:48\u202fpm - ',
 '15/03/2024, 8:05\u202fpm - ',
 '15/03/2024, 8:05\u202fpm - ',
 '15/03/2024, 9:54\u202fpm - ',
 '15/03/2024, 9:55\u202fpm - ',
 '15/03/2024, 10:16\u202fpm - ',
 '15/03/2024, 10:25\u202fpm - ',
 '16/03/2024, 4:58\u202fam - ',
 '16/03/2024, 4:58\u202fam - ',
 '16/03/2024, 4:59\u202fam - ',
 '16/03/2024, 4:59\u202fam - ',
 '16/03/2024, 4:59\u202fam - ',
 '16/03/2024, 4:59\u202fam - ',
 '16/03/2024, 4:59\u202fam - ',
 '16/03/2024, 4:59\u202fam - ',
 '16/03/2024, 4:59\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:00\u202fam - ',
 '16/03/2024, 5:01\u202fam - ',
 '16/03/2024, 5:01\u202fam - ',
 '16/03/2024, 5:01\u202fam - ',
 '16/03/2024, 5:01\u202fam - ',
 '16/03/2024, 5:01\u202fam - ',
 '16/03/2024, 5:01\u202fam - ',
 '16/03/2024, 5:01\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:02\u202fam - ',
 '16/03/2024, 5:03\u202fam - ',
 '16/03/2024, 5:03\u202fam - ',
 '16/03/2024, 5:03\u202fam - ',
 '16/03/2024, 5:03\u202fam - ',
 '16/03/2024, 5:03\u202fam - ',
 '16/03/2024, 5:04\u202fam - ',
 '16/03/2024, 5:04\u202fam - ',
 '16/03/2024, 5:04\u202fam - ',
 '16/03/2024, 5:04\u202fam - ',
 '16/03/2024, 5:05\u202fam - ',
 '16/03/2024, 5:05\u202fam - ',
 '16/03/2024, 5:05\u202fam - ',
 '16/03/2024, 5:06\u202fam - ',
 '16/03/2024, 5:06\u202fam - ',
 '16/03/2024, 5:06\u202fam - ',
 '16/03/2024, 5:06\u202fam - ',
 '16/03/2024, 5:06\u202fam - ',
 '16/03/2024, 5:07\u202fam - ',
 '16/03/2024, 5:07\u202fam - ',
 '16/03/2024, 5:08\u202fam - ',
 '16/03/2024, 5:08\u202fam - ',
 '16/03/2024, 5:09\u202fam - ',
 '16/03/2024, 5:10\u202fam - ',
 '16/03/2024, 5:10\u202fam - ',
 '16/03/2024, 5:10\u202fam - ',
 '16/03/2024, 5:11\u202fam - ',
 '16/03/2024, 5:41\u202fam - ',
 '16/03/2024, 5:41\u202fam - ',
 '16/03/2024, 5:42\u202fam - ',
 '16/03/2024, 5:43\u202fam - ',
 '16/03/2024, 5:46\u202fam - ',
 '17/03/2024, 12:42\u202fpm - ',
 '17/03/2024, 12:43\u202fpm - ',
 '17/03/2024, 12:43\u202fpm - ',
 '17/03/2024, 12:44\u202fpm - ',
 '17/03/2024, 2:33\u202fpm - ',
 '17/03/2024, 3:00\u202fpm - ',
 '17/03/2024, 3:00\u202fpm - ',
 '17/03/2024, 3:00\u202fpm - ',
 '17/03/2024, 3:00\u202fpm - ',
 '17/03/2024, 3:00\u202fpm - ',
 '17/03/2024, 3:00\u202fpm - ',
 '17/03/2024, 3:00\u202fpm - ',
 '17/03/2024, 3:01\u202fpm - ',
 '17/03/2024, 3:01\u202fpm - ',
 '18/03/2024, 8:56\u202fam - ',
 '18/03/2024, 8:56\u202fam - ',
 '18/03/2024, 10:17\u202fam - ',
 '18/03/2024, 10:17\u202fam - ',
 '18/03/2024, 1:06\u202fpm - ',
 '18/03/2024, 9:13\u202fpm - ',
 '18/03/2024, 9:21\u202fpm - ',
 '18/03/2024, 9:40\u202fpm - ',
 '18/03/2024, 10:26\u202fpm - ',
 '19/03/2024, 9:08\u202fpm - ',
 '19/03/2024, 9:42\u202fpm - ',
 '19/03/2024, 9:42\u202fpm - ',
 '19/03/2024, 10:50\u202fpm - ',
 '20/03/2024, 10:07\u202fpm - ',
 '20/03/2024, 10:07\u202fpm - ',
 '20/03/2024, 10:07\u202fpm - ',
 '20/03/2024, 10:32\u202fpm - ',
 '20/03/2024, 10:33\u202fpm - ',
 '20/03/2024, 10:33\u202fpm - ',
 '20/03/2024, 10:59\u202fpm - ',
 '20/03/2024, 10:59\u202fpm - ',
 '20/03/2024, 11:10\u202fpm - ',
 '20/03/2024, 11:15\u202fpm - ',
 '20/03/2024, 11:15\u202fpm - ',
 '20/03/2024, 11:17\u202fpm - ',
 '20/03/2024, 11:33\u202fpm - ',
 '20/03/2024, 11:33\u202fpm - ',
 '20/03/2024, 11:33\u202fpm - ',
 '20/03/2024, 11:33\u202fpm - ',
 '20/03/2024, 11:33\u202fpm - ',
 '20/03/2024, 11:33\u202fpm - ',
 '20/03/2024, 11:33\u202fpm - ',
 '20/03/2024, 11:34\u202fpm - ',
 '20/03/2024, 11:34\u202fpm - ',
 '20/03/2024, 11:34\u202fpm - ',
 '21/03/2024, 6:50\u202fam - ',
 '21/03/2024, 1:19\u202fpm - ',
 '21/03/2024, 1:46\u202fpm - ',
 '21/03/2024, 1:46\u202fpm - ',
 '21/03/2024, 9:57\u202fpm - ',
 '22/03/2024, 2:37\u202fpm - ',
 '22/03/2024, 4:20\u202fpm - ',
 '22/03/2024, 4:20\u202fpm - ',
 '22/03/2024, 4:21\u202fpm - ',
 '22/03/2024, 4:21\u202fpm - ',
 '22/03/2024, 4:21\u202fpm - ',
 '22/03/2024, 4:22\u202fpm - ',
 '22/03/2024, 4:22\u202fpm - ',
 '22/03/2024, 4:22\u202fpm - ',
 '22/03/2024, 4:25\u202fpm - ',
 '22/03/2024, 4:25\u202fpm - ',
 '22/03/2024, 5:27\u202fpm - ',
 '22/03/2024, 5:36\u202fpm - ',
 '22/03/2024, 5:40\u202fpm - ',
 '22/03/2024, 5:41\u202fpm - ',
 '22/03/2024, 5:43\u202fpm - ',
 '22/03/2024, 5:44\u202fpm - ',
 '22/03/2024, 10:35\u202fpm - ',
 '22/03/2024, 10:40\u202fpm - ',
 '22/03/2024, 10:41\u202fpm - ',
 '22/03/2024, 10:41\u202fpm - ',
 '22/03/2024, 10:41\u202fpm - ',
 '22/03/2024, 10:41\u202fpm - ',
 '22/03/2024, 10:42\u202fpm - ',
 '22/03/2024, 10:42\u202fpm - ',
 '22/03/2024, 10:42\u202fpm - ',
 '22/03/2024, 10:42\u202fpm - ',
 '22/03/2024, 10:42\u202fpm - ',
 '22/03/2024, 10:42\u202fpm - ',
 '22/03/2024, 10:42\u202fpm - ',
 '22/03/2024, 10:43\u202fpm - ',
 '22/03/2024, 10:43\u202fpm - ',
 '22/03/2024, 10:43\u202fpm - ',
 '22/03/2024, 10:43\u202fpm - ',
 '22/03/2024, 10:44\u202fpm - ',
 '22/03/2024, 10:44\u202fpm - ',
 '22/03/2024, 10:45\u202fpm - ',
 '22/03/2024, 10:45\u202fpm - ',
 '22/03/2024, 10:45\u202fpm - ',
 '22/03/2024, 10:45\u202fpm - ',
 '22/03/2024, 10:46\u202fpm - ',
 '23/03/2024, 10:53\u202fam - ',
 '25/03/2024, 12:19\u202fam - ',
 '25/03/2024, 12:20\u202fam - ',
 '25/03/2024, 4:34\u202fam - ',
 '25/03/2024, 4:35\u202fam - ',
 '25/03/2024, 4:35\u202fam - ',
 '25/03/2024, 4:50\u202fam - ',
 '25/03/2024, 4:50\u202fam - ',
 '25/03/2024, 4:58\u202fam - ',
 '25/03/2024, 9:53\u202fam - ',
 '25/03/2024, 10:42\u202fam - ',
 '25/03/2024, 10:43\u202fam - ',
 '25/03/2024, 10:43\u202fam - ',
 '25/03/2024, 10:48\u202fam - ',
 '25/03/2024, 11:38\u202fam - ',
 '25/03/2024, 11:38\u202fam - ',
 '25/03/2024, 3:01\u202fpm - ',
 '25/03/2024, 3:02\u202fpm - ',
 '27/03/2024, 5:23\u202fpm - ',
 '27/03/2024, 7:16\u202fpm - ',
 '27/03/2024, 7:20\u202fpm - ',
 '27/03/2024, 7:20\u202fpm - ',
 '27/03/2024, 7:33\u202fpm - ',
 '27/03/2024, 7:33\u202fpm - ',
 '31/03/2024, 3:41\u202fpm - ',
 '31/03/2024, 3:45\u202fpm - ',
 '31/03/2024, 4:34\u202fpm - ',
 '31/03/2024, 11:50\u202fpm - ',
 '01/04/2024, 4:11\u202fam - ',
 '01/04/2024, 4:11\u202fam - ',
 '01/04/2024, 4:12\u202fam - ',
 '01/04/2024, 4:12\u202fam - ',
 '01/04/2024, 4:13\u202fam - ',
 '01/04/2024, 4:14\u202fam - ',
 '01/04/2024, 4:15\u202fam - ',
 '01/04/2024, 4:15\u202fam - ',
 '01/04/2024, 5:22\u202fam - ',
 '01/04/2024, 6:27\u202fam - ',
 '01/04/2024, 6:29\u202fam - ',
 '03/04/2024, 12:49\u202fam - ',
 '03/04/2024, 4:13\u202fam - ',
 '03/04/2024, 4:41\u202fam - ',
 '03/04/2024, 4:41\u202fam - ',
 '03/04/2024, 6:20\u202fam - ',
 '03/04/2024, 10:21\u202fam - ',

In [8]:
data = data.replace("\u202f", " ")

In [10]:
print(len(messages))
print(len(dates))

4011
4010

In [23]:
min_len = min(len(messages), len(dates))

messages = messages[:min_len]
dates = dates[:min_len]

In [12]:
df = pd.DataFrame(
    list(zip(messages, dates)),
    columns=['user_message', 'message_date']
)

In [13]:
df['message_date'] = df['message_date'].str.replace('\u202f', ' ', regex=False)

df['message_date'] = pd.to_datetime(
    df['message_date'],
    format='%d/%m/%Y, %I:%M %p - '
)

df.rename(columns={'message_date': 'date'}, inplace=True)

print(df.head())

                                        user_message                date
0                                                    2024-02-28 14:12:00
1  Messages and calls are end-to-end encrypted. O... 2023-12-22 19:44:00
2  balbasuaar created group "Chivalrous gentlemen"\n 2024-02-28 14:12:00
3                             balbasuaar added you\n 2024-02-28 14:13:00
4           balbasuaar: Welcome my friend, welcome\n 2024-02-28 14:21:00

In [14]:
print("Dates:", len(dates))
print("Messages:", len(messages))

Dates: 4010
Messages: 4010

In [15]:
df.head()

                                        user_message                date
0                                                    2024-02-28 14:12:00
1  Messages and calls are end-to-end encrypted. O... 2023-12-22 19:44:00
2  balbasuaar created group "Chivalrous gentlemen"\n 2024-02-28 14:12:00
3                             balbasuaar added you\n 2024-02-28 14:13:00
4           balbasuaar: Welcome my friend, welcome\n 2024-02-28 14:21:00

In [16]:
import re

users = []
messages = []

for message in df['user_message']:
    message = str(message)  # safety against NaN / None

    entry = re.split(r'^([^:]+):\s', message, maxsplit=1)

    if len(entry) == 3:
        users.append(entry[1])
        messages.append(entry[2])
    else:
        users.append('group_notification')
        messages.append(message)

In [17]:
df.head()

                                        user_message                date
0                                                    2024-02-28 14:12:00
1  Messages and calls are end-to-end encrypted. O... 2023-12-22 19:44:00
2  balbasuaar created group "Chivalrous gentlemen"\n 2024-02-28 14:12:00
3                             balbasuaar added you\n 2024-02-28 14:13:00
4           balbasuaar: Welcome my friend, welcome\n 2024-02-28 14:21:00

In [18]:
df['user'] = users
df['message'] = messages
df.drop(columns=['user_message'], inplace=True)

df.head()

,date,user,message
0,2024-02-28 14:12:00,group_notification,
1,2023-12-22 19:44:00,group_notification,Messages and calls are end-to-end encrypted. O...
2,2024-02-28 14:12:00,group_notification,"balbasuaar created group ""Chivalrous gentlemen""\n"
3,2024-02-28 14:13:00,group_notification,balbasuaar added you\n
4,2024-02-28 14:21:00,balbasuaar,"Welcome my friend, welcome\n"

In [19]:
df['year']=df['date'].dt.year

In [20]:
df['hour']=df['date'].dt.hour

In [ ]:
df['minute']=df['date'].dt.minute

In [22]:
df.head()

,date,user,message,year,hour,minute
0,2024-02-28 14:12:00,group_notification,,2024,14,12
1,2023-12-22 19:44:00,group_notification,Messages and calls are end-to-end encrypted. O...,2023,19,44
2,2024-02-28 14:12:00,group_notification,"balbasuaar created group ""Chivalrous gentlemen""\n",2024,14,12
3,2024-02-28 14:13:00,group_notification,balbasuaar added you\n,2024,14,13
4,2024-02-28 14:21:00,balbasuaar,"Welcome my friend, welcome\n",2024,14,21